; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; [env:uno]
; platform = atmelavr
; board = uno
; framework = arduino
; monitor_speed = 9600
; monitor_eol = LF
; lib_deps =
;   chris--a/Keypad
;   marcoschwartz/LiquidCrystal_I2C
; src_filter = +<*> -<lab_2_2/>

; [env:mega]
; platform = atmelavr
; board = megaatmega2560
; framework = arduino
; monitor_speed = 9600
; monitor_eol = LF
; build_flags = -DLAB_2_2
; lib_deps =
;   feilipu/FreeRTOS
; build_src_filter = +<*> -<lab_2_1/> -<lab_1_1/> -<lab_1_2/> -<srv_os_sequential/> -<dd_keypad/> -<dd_lcd/> -<srv_lcd_keypad_stdio/>

; [env:mega_lab3]
; platform = atmelavr
; board = megaatmega2560
; framework = arduino
; monitor_speed = 9600
; monitor_eol = LF
; build_flags = -DLAB_3_1
; lib_deps =
;   feilipu/FreeRTOS
;   markruys/DHT
;   marcoschwartz/LiquidCrystal_I2C
; build_src_filter =
;   +<*>
;   -<lab_1_1/> -<lab_1_2/>
;   -<lab_2_1/> -<lab_2_2/>
;   -<srv_os_sequential/>
;   -<dd_keypad/> -<dd_button/> -<dd_sound/>
;   -<srv_lcd_keypad_stdio/>

; [env:mega_lab3_2]
; platform = atmelavr
; board = megaatmega2560
; framework = arduino
; monitor_speed = 9600
; monitor_eol = LF
; build_flags = -DLAB_3_2
; lib_deps =
;   feilipu/FreeRTOS
;   markruys/DHT
;   marcoschwartz/LiquidCrystal_I2C
; build_src_filter =
;   +<*>
;   -<lab_1_1/> -<lab_1_2/>
;   -<lab_2_1/> -<lab_2_2/>
;   -<lab_3_1/>
;   -<srv_os_sequential/>
;   -<dd_keypad/> -<dd_sound/>
;   -<srv_lcd_keypad_stdio/>

; [env:mega_lab4_1]
; platform = atmelavr
; board = megaatmega2560
; framework = arduino
; monitor_speed = 9600
; monitor_eol = LF
; monitor_echo = yes
; monitor_filters = send_on_enter
; build_flags = -DLAB_4_1 -DSERIAL_FREERTOS_YIELD
; lib_deps =
;   feilipu/FreeRTOS
;   marcoschwartz/LiquidCrystal_I2C
; build_src_filter =
;   +<*>
;   -<lab_1_1/> -<lab_1_2/>
;   -<lab_2_1/> -<lab_2_2/>
;   -<lab_3_1/> -<lab_3_2/>
;   -<srv_os_sequential/>
;   -<dd_keypad/> -<dd_sound/> -<dd_dht/> -<dd_ldr/>
;   -<srv_lcd_keypad_stdio/>

; [env:mega_lab4_2]
; platform = atmelavr
; board = megaatmega2560
; framework = arduino
; monitor_speed = 9600
; monitor_eol = LF
; monitor_echo = yes
; monitor_filters = send_on_enter
; build_flags = -DLAB_4_2 -DSERIAL_FREERTOS_YIELD
; lib_deps =
;   feilipu/FreeRTOS
;   marcoschwartz/LiquidCrystal_I2C
; build_src_filter =
;   +<*>
;   -<lab_1_1/> -<lab_1_2/>
;   -<lab_2_1/> -<lab_2_2/>
;   -<lab_3_1/> -<lab_3_2/>
;   -<lab_4_1/>
;   -<srv_os_sequential/>
;   -<dd_keypad/> -<dd_sound/> -<dd_dht/> -<dd_ldr/>
;   -<srv_lcd_keypad_stdio/>

[env:mega_lab5_1]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 9600
monitor_eol = LF
monitor_echo = yes
monitor_filters = send_on_enter
build_flags = -DLAB_5_1 -DSERIAL_FREERTOS_YIELD -Wl,-u,vfprintf -lprintf_flt -lm
lib_deps =
  feilipu/FreeRTOS
  marcoschwartz/LiquidCrystal_I2C
  markruys/DHT
build_src_filter =
  +<*>
  -<lab_1_1/> -<lab_1_2/>
  -<lab_2_1/> -<lab_2_2/>
  -<lab_3_1/> -<lab_3_2/>
  -<lab_4_1/> -<lab_4_2/>
  -<lab_5_2/>
  -<srv_os_sequential/>
  -<dd_keypad/> -<dd_sound/> -<dd_ldr/> -<dd_led_pwm/>
  -<ctrl_pid/>
  -<srv_lcd_keypad_stdio/>

; [env:mega_lab5_2]
; platform = atmelavr
; board = megaatmega2560
; framework = arduino
; monitor_speed = 9600
; monitor_eol = LF
; monitor_echo = yes
; monitor_filters = send_on_enter
; build_flags = -DLAB_5_2 -DSERIAL_FREERTOS_YIELD -Wl,-u,vfprintf -lprintf_flt -Wl,-u,vfscanf -lscanf_flt -lm
; lib_deps =
;   feilipu/FreeRTOS
;   marcoschwartz/LiquidCrystal_I2C
; build_src_filter =
;   +<*>
;   -<lab_1_1/> -<lab_1_2/>
;   -<lab_2_1/> -<lab_2_2/>
;   -<lab_3_1/> -<lab_3_2/>
;   -<lab_4_1/> -<lab_4_2/>
;   -<lab_5_1/>
;   -<srv_os_sequential/>
;   -<dd_keypad/> -<dd_sound/> -<dd_dht/> -<dd_actuator/>
;   -<srv_lcd_keypad_stdio/>

